# Generated by Django 3.1.7 on 2021-03-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_management', '0002_auto_20210324_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='door_url',
            field=models.URLField(default='https://localhost:3000/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='door',
            name='password',
            field=models.CharField(default='password', max_length=200),
            preserve_default=False,
        ),
    ]
