# Generated by Django 3.1.7 on 2021-03-25 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_management', '0003_auto_20210324_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='door_id',
            field=models.CharField(default='door', max_length=200),
            preserve_default=False,
        ),
    ]
