# Generated by Django 3.1.7 on 2021-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_management', '0004_door_door_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='closed_image',
            field=models.ImageField(upload_to='static/door_images'),
        ),
        migrations.AlterField(
            model_name='door',
            name='open_image',
            field=models.ImageField(upload_to='static/door_images'),
        ),
    ]
