# Generated by Django 3.1.7 on 2021-03-25 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_management', '0005_auto_20210325_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='closed_image',
            field=models.ImageField(upload_to='door_management/static/door_images'),
        ),
        migrations.AlterField(
            model_name='door',
            name='open_image',
            field=models.ImageField(upload_to='door_management/static/door_images'),
        ),
    ]
