# Generated by Django 3.1.7 on 2021-03-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_management', '0006_auto_20210325_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='door_id',
        ),
        migrations.RemoveField(
            model_name='door',
            name='door_url',
        ),
        migrations.AddField(
            model_name='door',
            name='door_slug',
            field=models.SlugField(default='my_door'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_slug',
            field=models.SlugField(default='my_room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='workspace_slug',
            field=models.SlugField(default='my_workspace'),
            preserve_default=False,
        ),
    ]
