# Generated by Django 3.1.7 on 2021-03-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door_management', '0007_auto_20210325_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='door_url',
            field=models.URLField(default='localhost:3000'),
            preserve_default=False,
        ),
    ]
