# Generated by Django 3.1.7 on 2021-03-26 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('door_management', '0008_door_door_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='door_url',
        ),
    ]
